version: 0.0
os: linux	
files:	
  - source: /index.html	  
    destination: /home/ec2-user    
hooks:	
  BeforeInstall:	 
    - location: scripts/start_server	    
      timeout: 300	     
      runas: ec2-user	      
